version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: wallet_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_db
    ports:
      - "3306:3306"
    volumes:
      - wallet_data:/var/lib/mysql

  api:
    build: .
    container_name: wallet_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: wallet_db
      DB_PORT: 3306
    command: npm run dev

volumes:
  wallet_data:
